demo/demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gallery/', include('gallery.urls'))
]

demo/gallery/urls.py
from django.conf.urls import url
from . import views

app_name = 'gallery' # important to include all names inside the namespace for templates. Example: gallery:index

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
    url(r'^(?P<id>[0-9]+)$', views.detail, name='detail'),
]

demo/gallery/models.py
from django.db import models

class Gallery(models.Model):
    name = models.CharField(max_length=70)
    description = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name + ' - ' + self.description

class Photo(models.Model):
    name = models.CharField(max_length=70)
    description = models.CharField(max_length=255)
    gallery = models.ForeignKey(Gallery)
    
    def __str__(self):
        return self.name + ' - ' + self.description

demo/gallery/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from django.http import Http404, HttpResponseBadRequest
from .models import Gallery
from django.views.generic import View
#from django.template import loader

#def index(request):
#    galleries = Gallery.objects.all()
#    html = ''
#    for gallery in galleries:
#        url = '/gallery/' + str(gallery.id) + '/'
#        html += '<a href="' + url + '">' + gallery.name + '</a><br>'
#        
#    return HttpResponse(html)

#def index(request):
#    galleries = Gallery.objects.all()
#    template = loader.get_template('gallery/index.html')
#    context = {
#        'galleries' : galleries
#    }
#    
#    return HttpResponse(template.render(context, request))

#def index(request):
#    galleries = Gallery.objects.all()
#    context = {'galleries' : galleries}
#    return render(request, 'gallery/index.html', context)

#def create(request):
#    try:
#        gallery = Gallery()
#        gallery.name = request.POST['name']
#        gallery.description = request.POST['description']
#        gallery.save()
#    except (KeyError):
#        return HttpResponseBadRequest("Error al recibir el formulario")
#        
#    return index(request)

class index(View):
    def get(self, request):
        galleries = Gallery.objects.all()
        context = {'galleries' : galleries}
        return render(request, 'gallery/index.html', context)
    
    def post(self, request):
        try:
            gallery = Gallery()
            gallery.name = request.POST['name']
            gallery.description = request.POST['description']
            gallery.save()
        except (KeyError):
            return HttpResponseBadRequest("Error al recibir el formulario")
            
        return self.get(request)

def detail(request, id):
    try:
        gallery = Gallery.objects.get(pk=id)
    except Gallery.DoesNotExist:
        raise Http404("This gallery does not exists")
    return render(request, 'gallery/details.html', {'gallery':gallery})

demo/gallery/templates/gallery/details.html
<h1>{{ gallery.name }}</h1>
<a href="{% url 'gallery:index' %}">Atrás</a>
<h3>{{ gallery.description }}</h3>

<ul>
    {% for photo in gallery.photo_set.all %}
        <li>{{ photo.name }} - {{ photo.description }}</li>
    {% endfor %}
</ul>

demo/gallery/templates/gallery/index.html
{%  load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'gallery/style.css' %}"
{% if galleries %}
    <ul>
        {% for gallery in galleries %}
        <!-- the keyword used in the url patter is the one specified in the urls file appended after the app_name in the same file -->
        <li><a href="{% url 'gallery:detail' gallery.id %}">{{ gallery.name }}</a></li>
        {% endfor %} 
    </ul>
{% else %}
    <h2>You don't have any gallery yet</h2>
{% endif %}
<form action="{% url 'gallery:index' %}" method="post">
    {% csrf_token %}
    name: <input type="text" name="name" /> <br />
    description: <input type="text" name="description" /> <br />
    <input type="submit" />
</form>